// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTZ9jQoLNdTpuwFFfWU5lQvAI4qx0gDZE',
    appId: '1:983524038846:web:a071f799b237e3430926ef',
    messagingSenderId: '983524038846',
    projectId: 'time-track-mbe',
    authDomain: 'time-track-mbe.firebaseapp.com',
    storageBucket: 'time-track-mbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhTU6vJ4G69gkmbiA7CbEvNykxXuq9oxU',
    appId: '1:983524038846:android:a573779e5cbf2d100926ef',
    messagingSenderId: '983524038846',
    projectId: 'time-track-mbe',
    storageBucket: 'time-track-mbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi7AWnLXzYsgLoUmO0sWoXpR0ICqIUDMY',
    appId: '1:983524038846:ios:d6cec823eae171d30926ef',
    messagingSenderId: '983524038846',
    projectId: 'time-track-mbe',
    storageBucket: 'time-track-mbe.firebasestorage.app',
    iosBundleId: 'com.example.timeTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi7AWnLXzYsgLoUmO0sWoXpR0ICqIUDMY',
    appId: '1:983524038846:ios:d6cec823eae171d30926ef',
    messagingSenderId: '983524038846',
    projectId: 'time-track-mbe',
    storageBucket: 'time-track-mbe.firebasestorage.app',
    iosBundleId: 'com.example.timeTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTZ9jQoLNdTpuwFFfWU5lQvAI4qx0gDZE',
    appId: '1:983524038846:web:f1d44558400d8d2b0926ef',
    messagingSenderId: '983524038846',
    projectId: 'time-track-mbe',
    authDomain: 'time-track-mbe.firebaseapp.com',
    storageBucket: 'time-track-mbe.firebasestorage.app',
  );

}